export class TwitItem{
  num: number;
  name: string;
  date: string;
  id: string;
  idTotal: number;
  idNum: number;
  anchors: any;
  content: string;
  isAdded: boolean;
  parent: number;
  isShow: boolean;
  resColor: string;
  resFontSize: string;
  resSelect: string;
  resBackgroundColor = 'transparent';
  resHovergroundColor = '#e2e2e2';
  idBackgroundColor = '#fff';
  idColor = '#000';
  moveMarkColor = '#999';
  idClassNoSelect = '';
  hasImage = false;
  isFiltered = false;
  originalIndex: number;
  anchorCount: number;
  isEdit: boolean;
  resMenu: number;
  isMenuOpen: boolean;
  isRemark: boolean;
  isSearched = false;
  isNotice: boolean;
  anchorLevel: number;
  numBackground = 'transparent';
}
